\ProvidesClass{CommonJobDoc}
\LoadClass{article}

\RequirePackage[margin=0.5in]{geometry}
\RequirePackage{titlesec}
\usepackage{fontspec}
\usepackage{enumitem}
\usepackage{multicol}

\setmainfont{Arial}
\setlength\parindent{0pt}
\titlespacing\section{0pt}{5pt plus 2pt minus 2pt}{0pt plus 0pt minus 0pt}
\raggedbottom
\setlength\tabcolsep{0pt}
\setlist{nolistsep}
\setlength{\textfloatsep}{0pt}
\setlength{\parskip}{2pt}
\setlength{\floatsep}{0pt}
\setlength{\intextsep}{0pt}
\setlength{\multicolsep}{0pt}
